###### delete car
POST http://localhost:3000/api/removeCar HTTP/1.1
content-type: application/json

{
    "regNumber": "CL 76173"
}

##### add car api 
POST http://localhost:3000/api/addCar HTTP/1.1
content-type: application/json

{
    "color": "blue",
    "make": "Toyota",
    "model":"Corolla",
    "regNumber": "CJ 76173"
}

#####  popular cars api
GET http://localhost:3000/api/popularCar HTTP/1.1
content-type: application/json

##### read cars data
GET http://localhost:3000/api/Cars HTTP/1.1
content-type: application/json


###### update existing cars
